Support Trio out-of-the-box
jd/tenacity pull request #295
Opened 2021-04-25 22:28 UTC by njsmith

This PR makes `@retry` just work when running under Trio.

For now, I added `trio` to the test deps in tox.ini, so we can test
it. The code is also designed to handle things gracefully if trio
isn't installed, but currently there's not any automated test for
that... how would you like to handle this? Maybe add another
test environment without trio?

2021-04-27 14:37 UTC, jd submitted a review, later dismissed
Yeah I think we should cover both. Just add a new tox scenario with and without trio :)

2021-04-27 16:11 UTC, njsmith commented
@jd How's this look?

2021-04-27 19:02 UTC, jd requested changes
I think it's good though I'd prefer to have `py39-trio` rather than `notrio` 😁

2021-04-27 22:32 UTC, njsmith commented
Fair enough!

2021-04-27 22:33 UTC, njsmith commented
Made that change and also rebased on latest master, to make mergify happy

2021-07-09 06:49 UTC, penguinolog commented on .circleci/config.yml
> +            tox -e py39-notrio
inconsistent with `tox.int` (`py39-trio` for `trio` and normal python versions for other)

2023-11-15 01:40 UTC, chrisjwelly commented
Hello @njsmith ! I understand it has been over 2 years since this PR was opened. Might there be any chance of a follow-up to support trio out of the box? 

I think this feature is great, as it can be easy to forget add `trio.sleep` argument to the retry.

2023-12-28 12:04 UTC, SysuJayce commented
I also wonder how to use tenacity with trio.

If I use tenacity.retry() as a decorator for a async function, how can I check the result of the async function via `tenacity.retry_if_result()`? And then I got an error `TypeError: argument of type 'coroutine' is not iterable, xxx was never awaited`.

Even if I change my retry condition to `retry_if_exception`, I got another error `TypeError: object NoneType can't be used in 'await' expression`.

Please give me some tips, thank you guys~~~

2024-10-23 10:43 UTC, jakkdl commented
This can be closed, as it was implemented with #463

2024-10-23 14:46 UTC, closed without merging