Add retry_except_exception_type()
jd/tenacity pull request #300
Opened 2021-05-17 14:00 UTC by henry0312

Fixes #256

2021-05-17 14:27 UTC, jd requested changes
Small typo

2021-05-17 14:27 UTC, jd commented on releasenotes/notes/add-retry_except_exception_type-31b31da1924d55f4.yaml
> +  - Add ``retry_except_exception_type()`` that allows us to retry if a raised exception doesn't match given exceptions.
```suggestion
  - Add ``retry_except_exception_type()`` that allows to retry if a raised exception doesn't match given exceptions.
```

2021-05-17 14:27 UTC, jd commented on tenacity/retry.py
> +    """Retries excpet an exception has been raised of one or more types."""
```suggestion
    """Retries except an exception has been raised of one or more types."""
```

2021-05-17 15:42 UTC, jd submitted a review, later dismissed

2021-05-17 18:55 UTC, asqui commented
I think we can be clearer on the naming of this method to better communicate what it is doing.

Is this implementing the `retry_if_exception_not_of_type` which was propossed in the discussion of #137?

2021-05-18 00:18 UTC, henry0312 commented
> Is this implementing the retry_if_exception_not_of_type which was propossed in the discussion of #137?

Yes, it it.
Though @jd approved this, would it be good to rename `retry_except_exception_type` to `retry_if_exception_not_of_type`?

2021-05-18 13:47 UTC, jd commented
I'm fine with whatever.
We need to fix the CI not running issue to merge anything at this point 😢

2021-05-18 15:43 UTC, asqui commented
I do think `retry_if_exception_not_of_type` would fit better amongst the existing family of related `retry_*` methods:

- `retry_if_exception`
- `retry_if_exception_type`
- `retry_unless_exception_type` -- would have been better named `retry_if_not_exception_type`, but yolo.
- `retry_if_result`
- `retry_if_not_result`
- `retry_if_exception_message`
- `retry_if_not_exception_message`

In particular, I think it's important that the new method, whatever it's called, is clearly set apart from `retry_unless_exception_type` given the subtle but important differences between the two (as discussed, at length, in #137).

More generally, I'm slightly alarmed by the "I'm fine with whatever" remark. I worry that without careful consideration of usability, adoption of this library will be hampered in the future. (This is speaking as someone who has tried to bring tenacity in to an existing codebase which already has numerous disparate approaches to retry logic, and the complexity/usability concerns around tenacity have certainly been a barrier to adoption.)

2021-05-19 11:51 UTC, henry0312 commented
A relation between `retry_if_exception_type()` and `retry_except_exception_type()` is the same with one between `retry_if_exception_message()` and `retry_if_not_exception_message()`, since the implementation of `retry_except_exception_type()` is the essentially same with that of `retry_if_not_exception_message()`.
(cf. https://github.com/jd/tenacity/blob/master/tenacity/retry.py#L125 and https://github.com/jd/tenacity/blob/master/tenacity/retry.py#L167)

Therefore, if I would rename, I think `retry_if_not_exception_type` is better than `retry_if_exception_not_of_type`, that follows the named rule of `retry_if_not_exception_message`.

---
For details,

- `retry_if_exception_type(T)`

`T` is **included** in conditons of retry.

- `retry_except_exception_type(T)`

`T` is **excluded** from conditions of retry.
In other words, `T` is **not included** in condtions of retry.

- `retry_if_exception_message(A)`

`A` is **included** in conditons of retry.

- `retry_if_not_exception_message(A)`

`A` is **excluded** from conditions of retry.
This means that `T` is **not included** in condtions of retry.

By the way,

- `retry_unless_exception_type(T)`

Retry **until** `T` is raised.
(`T` is expected to be raised to stop retry)

---

I'm not good ad English and I'm sorry for my bad English.

2021-05-23 17:26 UTC, asqui commented
@henry0312 Thanks for taking the time to look at this in such detail.

I agree that `retry_if_not_exception_type` fits better with the existing naming conventions.

P.S. Don't apologise, your english is great! (I have no reason to believe you're not a native speaker!)

2021-05-24 07:40 UTC, henry0312 commented
@jd @asqui I just renamed `retry_except_exception_type` to `retry_if_not_exception_type`

2021-05-26 07:54 UTC, jd approved these changes

2021-05-26 08:47 UTC, henry0312 commented
@jd I just fixed tests!

2021-05-26 12:32 UTC, jd approved these changes

2021-05-26 12:33 UTC, merged

2021-05-26 13:41 UTC, henry0312 commented
@jd Thank you for reviewing and merging.
Do you have a plan for a new [release](https://github.com/jd/tenacity/releases)?

2021-07-07 20:17 UTC, william-silversmith commented
Likewise! Thanks so much jd and all that contributed! I would start using this feature once the next release is out.