Added CLI wrapper
jd/tenacity pull request #366
Opened 2022-10-09 18:20 UTC by Yureien

Tenacity can now be used as a CLI app to retry shell scripts or apps!

Closes https://github.com/jd/tenacity/issues/279

It's not yet complete, some of the advanced functions are left (such as exponential and random wait functions, thinking of a good way to implement those). A changelog is left too, but I wanted your reviews first on whether this is a good change, and if I am following the proper styling/coding guidelines or not.

2024-03-02 07:39 UTC, jd requested changes
Not convinced about the need/usage, but why not. Though there's no test so I'm a bit reluctant to merge that.

2024-03-02 07:39 UTC, jd commented on .gitignore
> +venv/
not needed

2024-03-02 07:39 UTC, jd commented on bin/tenacity
> +from tenacity.__main__ import main
use console scripts

2024-03-02 07:39 UTC, jd commented on setup.py
> +    scripts=["bin/tenacity"],
use console scripts

2024-03-02 13:06 UTC, asqui commented on tenacity/__main__.py
> +    help="Status code that should be ignored. This argument can be called multiple times.",
```suggestion
    help="Non-zero status code that should be ignored. This argument can be called multiple times.",
```

2024-03-02 13:07 UTC, asqui commented
This seems like a nice feature!

Worth mentioning in the release notes, and would be good to have some test coverage.

2024-07-05 07:23 UTC, closed without merging

2024-07-05 07:23 UTC, jd commented
Not updated in a while.