fix: remove __iter__ from AsyncRetring
jd/tenacity pull request #387
Opened 2023-01-31 16:24 UTC by sileht

This method doesn't make sense for AsyncRetrying. And it's even more
vicious as:

```
for attempts in AsyncRetrying():
    with attempts:
        await do_for_a_while()
```

will work, but sleep(XXX) coroutine will never be awaited and the call is
retried instantly.

This change removes the __iter__ method from AsyncRetrying.

2023-01-31 19:17 UTC, jd requested changes
Can you add a test for this?

2023-02-01 11:36 UTC, jd approved these changes

2023-02-01 13:33 UTC, jd commented
@sileht can you add a release note?

2023-02-06 09:29 UTC, jd approved these changes

2023-02-06 09:46 UTC, sileht commented
@mergifyio update

2023-02-06 10:28 UTC, jd approved these changes

2023-02-06 10:29 UTC, merged